baseURL = 'https://qschwagle.github.io/'
languageCode = 'en-us'
title = "Quinton's Personal Blog"
theme = "hugo-PaperMod"

[outputs]
home = ['HTML', 'RSS', 'JSON']

[params]
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Quinton Schwagle"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts"

[[params.profileMode.buttons]]
name = "Github"
url = "https://github.com/qschwagle"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/qschwagle"

[[params.socialIcons]]
name = "GitLab"
url = "https://gitlab.com/qschwagle"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/quinton-schwagle-0301431b3"

[menu]

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects"
weight = 30

[[menu.main]]
identifier = "useful-links"
name = "useful-links"
url = "useful-links"
weight = 40
